### ISSUE TITLE
Curved edge of find in page prompt is broken

### ISSUE THREAD

**Issue by BionicBison05** [sagars007/starry-fox#1]
<img width="1286" alt="Screen Shot 2021-12-24 at 1 07 33 PM" src="https://user-images.githubusercontent.com/93722725/147368230-98cd428e-de0e-4ef5-a720-8848219895ee.png">
The curved edge appears to be flipped.

**Comment by sagars007** [comment]
It looks fine in my browser. Do you have any other code in userChrome.css that might be conflicting? Or it might be a problem in MacOS? I'm unable to test it on a MacOS system as I only have a Win 11 PC.

![image](https://user-images.githubusercontent.com/56472130/147402034-5c7feedb-10c1-4faf-9be7-738b6e40d49e.png)

**Comment by gitgizmo7** [comment]
I have no other userchrome.css code, I just copied what was in the repo. It's probably an issue in the macOS version of Firefox.
